### ISSUE TITLE
安装报错了...?

### ISSUE THREAD

**Issue by fewpiwork** [kakuilan/kgo#1]
go get -u -v github.com/kakuilan/kgo
go: finding golang.org/x/net latest
go: finding github.com/modern-go/concurrent latest
go: finding golang.org/x/crypto latest
github.com/kakuilan/kgo
# github.com/kakuilan/kgo
../../../golang/pkg/mod/github.com/kakuilan/kgo@v0.0.1/os.go:258:12: undefined: syscall.Sysinfo_t
../../../golang/pkg/mod/github.com/kakuilan/kgo@v0.0.1/os.go:259:10: undefined: syscall.Sysinfo

**Comment by kakuilan** [comment]
没错啊
```sh
$ go get -u -v github.com/kakuilan/kgo
go: finding golang.org/x/net latest
go: finding golang.org/x/crypto latest
go: finding github.com/modern-go/concurrent latest
go: downloading golang.org/x/crypto v0.0.0-20200128174031-69ecbb4d6d5d
go: downloading golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa
go: extracting golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa
go: extracting golang.org/x/crypto v0.0.0-20200128174031-69ecbb4d6d5d
golang.org/x/net/html/atom
golang.org/x/crypto/blowfish
golang.org/x/net/html
golang.org/x/crypto/bcrypt
github.com/kakuilan/kgo
```
你可能需要：
- 支持go mod
- 被墙了,使用goproxy.io代理

另外注意：  
*本库的主分支更改了一些方法名,因此godoc上的文档会与v0.0.1实际代码有差别,以后升级时须手工更改已变化的方法名*

**Comment by fewpiwork** [comment]
undefined: syscall.Sysinfo_t
undefined: syscall.Sysinfo

也许因为我是osx?

**Comment by kakuilan** [comment]
这个不清楚了，没用过osx

**Comment by kakuilan** [comment]
@fewpiwork v0.0.2已发布
