### ISSUE TITLE
go get 的时候出现错误

### ISSUE THREAD

**Issue by tlkt** [kakuilan/kgo#2]
$ go get -u github.com/kakuilan/kgo
# github.com/kakuilan/kgo
../../pkg/mod/github.com/kakuilan/kgo@v0.1.2/os.go:303:12: undefined: syscall.Sysinfo_t
../../pkg/mod/github.com/kakuilan/kgo@v0.1.2/os.go:304:10: undefined: syscall.Sysinfo

**Comment by Mikaelemmmm** [comment]
same problem

**Comment by isslii** [comment]
+ 1

**Comment by kakuilan** [comment]
目前已支持linux/darwin/windows，你们再试试
