### ISSUE TITLE
希望有随机插入切片或者数组任意位置的函数

### ISSUE THREAD

**Issue by a67793581** [kakuilan/kgo#5]
希望有随机插入切片或者数组任意位置的函数

**Comment by kakuilan** [comment]
你插入元素后，可以使用KArr.ArrayShuffle打乱顺序。
写成一个函数大概也是这样的处理，所以我觉得没有必要。

**Comment by a67793581** [comment]
不太一样 我希望原始数据有序 插入数据随机 比如默认普通元素10个 随机插入2个特殊元素 这样原来的10个还是顺序的

**Comment by kakuilan** [comment]
感觉这样的需求没有普遍性，所以还是先不加了
